### ISSUE TITLE
Project clean and bintray clean up

### ISSUE THREAD

**Issue by basejump** [yakworks/idea-bank#1]
https://bintray.com/9ci/maven

- [ ] are all the other projects here used? Delete them if they are garbage keeping in mind that the files and dirs should be deleted first. If they are used then put a link to where they came from and a note on why they are here. 

under https://bintray.com/9ci/grails-plugins/

- [x] freemarker 
  - clean up links to point to yakworks fork
  - fix package name to be the normal org.grails.plugins
  - change the grails3 branch to be master, and make master the grails2.5
  - setup travis and redo the dir structure to be our standard one
  - release and request inclusion in https://bintray.com/grails/plugins 

- [x] grails-jasper-reports
  - the github project name is fine, the java package name is fine, the name of the maven group and package needs to change. its currently `compile 'nine.jasper:grails-jasper-reports:3.0.3'` and should be `compile 'org,grails.plugins:jasper-reports:3.0.3'`
  - re-org into our standard package structure. rename test-projects to examples, etc..
  - setup travis properly
  - remove old bad previously release files from bintray. IE the nine/jasper dir should not show up here https://dl.bintray.com/9ci/grails-plugins/nine/
  - update Readme.md with better instructions on using the plugin
  - release and request inclusion in https://bintray.com/grails/plugins 

- [x] https://bintray.com/9ci/grails-plugins/quartz-config-scheduler
  - see https://github.com/yakworks/quartz-config-scheduler/issues/1

- [x] https://bintray.com/9ci/grails-plugins/spring-security-eventlog
  - what is this? do we use it? why is it in the 9ci bintray. If its in our bintray then it should be under yakworks
 - groupid is grails.plugins and does not follow the org.grails.plugins standard for grails 3

- [x] view-tools
  - promote to 1.0 and remove the grails3 postfix on this
  - make sure it works with grails 3.3.2

I created a snapshots bintray here https://bintray.com/9ci/snapshots. is there any reason we cannot use that instead of our repo.9ci for snapshots? seems I see others doing it. if no objections then get that setup as your cleaning up these projects and make sure there is a gradle example about how to use it in each projects readme for snapshots. IE https://dl.bintray.com/9ci/snapshots

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/672495572651867/672614152710300)
┆Due Date: 2018-06-04

**Comment by snimavat** [comment]
@basejump bintray maven repo has paypal-base,webservices-api etc which are not in mavencentral or jcenter, these are used by paymentgate-way this are old libs which were under libs/ directory in grails2. So they are published on bintray for grails3

```
    compile "nine:jaxb-impl:9ci"
    compile "nine:paypal-base:9ci"
    compile "nine:paysimple:9ci"
    compile "nine:webservices-api:9ci"
    compile "nine:webservices-extra-api:9ci"

```

**Comment by basejump** [comment]
ok fine, as I noted above " If they are used then put a link to where they came from and a note on why they are here." meaning, put your comments/info in bintray not here.

**Comment by snimavat** [comment]
Jasper reports 3.0.4 released and requested inclusion to grails plugins

**Comment by snimavat** [comment]
@basejump spring-security-eventlog is used to log security events, and we use it in rcm.
It was existing plugin from grails 2.x that we upgraded to grails 3. 
I transffered the fork to yakworks. as it was existing plugin, should we change the group id to org.grails.plugins or keep existing ?

**Comment by basejump** [comment]
Lets move away from using "https://raw.githubusercontent.com/yakworks/grails-common-build/master". Its to hard to debug especially when internet access is non-existant. either don't use if not needed or do what graph-ql does and we do in gorm-tools by putting them in the gradle dir. see https://github.com/grails/gorm-graphql/tree/master/gradle and out gorm-tools
