### ISSUE TITLE
Travis to only build docs if there are changes under that dir

### ISSUE THREAD

**Issue by basejump** [yakworks/idea-bank#2]
instead of building the docs and publishing to gh-pages each check in, only do it if there are changes in the docs dir. Vis versa as well. if only the docs changed then don't do a full build/test.

see commit here for what looks like is an example of how one way can be done. see before_install here https://github.com/ThomasWaldmann/borg/blob/master/.travis.yml

**Comment by snimavat** [comment]
Done, on master. https://github.com/yakworks/view-tools/commit/7517ea7711ab3e256dc1817783aab984c518f012
